### ISSUE TITLE
install issue on raspberry pi zero W - npm path? 

### ISSUE THREAD

**Issue by ejangelico** [henhen724/node-red-widaq#1]
Attempting to install with `npm i node-red-widaq` leads to an error during the sub-install of install-mode-graphqlschema.js that claims npm is not on the system path. This may be true - can't find what to add to my PATH variable to fix this, though it is a strange error to throw as npm installs other node-red nodes just fine. Log file and screenshot of error output are attached. 
[2020-11-25T18_13_03_825Z-debug.log](https://github.com/henhen724/node-red-widaq/files/5598635/2020-11-25T18_13_03_825Z-debug.log)
<img width="931" alt="Screen Shot 2020-11-25 at 10 14 17 AM" src="https://user-images.githubusercontent.com/18689976/100268860-873c8180-2f0a-11eb-840c-62392ed54b8b.png">

**Comment by henhen724** [comment]
Solution: Update to version >=0.9.4.

Cause:  The installation script used the "where" command to check whether npm was installed, but this only available in CMD.  Changed the "where npm" command to "npm --version."
